Repository bsc-quantic/Tenet.jl, pull requests merged in 2024-10, with the labels that each got.

#213 Fix `TensorNetwork` serialization
  src/TensorNetwork.jl
  test/Project.toml
  test/TensorNetwork_test.jl
Labels: backport

#219 Fix index dimension mismatch in `TensorNetwork` construction
  src/TensorNetwork.jl
  test/TensorNetwork_test.jl
Labels: bug

#218 Implement an MPS method initializing the tensors to identity (copy-tensors)
  src/Ansatz/MPS.jl
  test/Ansatz_test.jl
  test/MPS_test.jl
Labels: enhancement

#217 Test transformations
  test/Transformations_test.jl
Labels: bug, ci/cd

#224 Set minimum supported Julia version to 1.10
  .github/workflows/CI.yml
  .github/workflows/format-check.yml
  .github/workflows/format-pr.yml
  Project.toml
Labels: ci/cd, triage
